### ISSUE TITLE
Vehicle duplication -- Fixed

### ISSUE THREAD

**Issue by neoreturns** [JustAnotherModder/JAM_Garage#1]
Firstly many thanks for your scripts, they are much better than the original eden_garage.

I'm having an issue whereby the vehicle is being stored, still remains in the game world - but then is also stored in the garage, allowing you to duplicate the vehicle unlimited times. I have a feeling its something with our database, but if you can point me in the write direction it would be helpful. Many thanks.

screenshot: [https://imgur.com/a/EyRNjx6](url)

**Comment by JustAnotherModder** [comment]
Thanks for the kind words.

Just to make sure, you are using essentialmode, es_extended and esx_vehicleshop which has, in your database, added a table called `owned_vehicles`?

Also, I can't see your screenshot.

**Comment by neoreturns** [comment]
I just updated and tested again, unfortunately have the same issue, appreciate your reply, the logic in your script is much better than the others so I hope we can find the reason for the issue. I've double checked all columns in the DB, they are the right structure.

I took a vehicle out and it still says its in the Garage regardless, allowing me to take multiple out. I have the owned_vehicles table and all the relevant columns.

![image](https://user-images.githubusercontent.com/34321024/55158724-db082d80-515f-11e9-8626-ed78ade0bb36.png)

**Comment by JustAnotherModder** [comment]
Are you seated when you perform the storing of the vehicle?

**Comment by neoreturns** [comment]
![image](https://user-images.githubusercontent.com/34321024/55158778-fbd08300-515f-11e9-9780-36f1a69fd149.png)

Yes, I am in the driver seat, but it kicks me from the car, stores the car and doesnt delete it from the game world.

**Comment by neoreturns** [comment]
As your here now (thankfully) i will load up twitch and stream the issue.

https://www.twitch.tv/minjah

**Comment by JustAnotherModder** [comment]
I'm watching you now, can't comment

**Comment by JustAnotherModder** [comment]
You're definitely using es_essential and essentialmode?

**Comment by prajeetware** [comment]
Yes correct

**Comment by neoreturns** [comment]
If you have time, maybe discord is easier, we are at https://discord.gg/b3JAvTw - appreciate your help.

**Comment by JustAnotherModder** [comment]
Okay, can you send me a screenshot of your owned_vehicles table

**Comment by prajeetware** [comment]
![image](https://user-images.githubusercontent.com/34321024/55159321-ffb0d500-5160-11e9-958f-7d5b822143bf.png)

**Comment by prajeetware** [comment]
![image](https://user-images.githubusercontent.com/34321024/55159349-148d6880-5161-11e9-9b0c-78a263c674ee.png)

**Comment by JustAnotherModder** [comment]
Okay. I've tested it thoroughly with the latest release of esx_vehicleshop. If you have installed all of the dependencies correctly, there should be no issues with using the latest release of this mod. Even if you had installed eden_garage before this, it should change your database `state` row into a int value, which may have been causing the issues before. I'll re-post this in your discord for convenience.

**Comment by neoreturns** [comment]
Its not compatible with;  NoCarJack, EngineToggle, CarCleanUp
