### ISSUE TITLE
Cars not being stored in impound when impounded using esx_policejob

### ISSUE THREAD

**Issue by hyp3rstrike** [JustAnotherModder/JAM_Garage#3]
Using ESX_PoliceJob action menu (F6) to impound a car, and the notification says impounded however there is car listing in either impound UI or Garage.

JAMSTATE is set to 2 for the related vehicles in mysql however nothing is showing in the menu.

**Comment by KilluaZoldyck0099** [comment]
Did you find any solution to this??

**Comment by JustAnotherModder** [comment]
`function ImpoundVehicle(vehicle)
    --local vehicleName = GetLabelText(GetDisplayNameFromVehicleModel(GetEntityModel(vehicle)))
    local vehicleProps = ESX.Game.GetVehicleProperties(vehicle)
    TriggerServerEvent('JAM_Garage:ChangeState', vehicleProps.plate, 2)
    ESX.Game.DeleteVehicle(vehicle) 
    ESX.ShowNotification(_U('impound_successful'))
    CurrentTask.Busy = false
end`

Replace that function in police job. Should work.

**Comment by KilluaZoldyck0099** [comment]
Could you tell me what to do more specific?? Basicaly I want when cars from jobs are being impounded return to garage

**Comment by FlamingOcean** [comment]
also why when a car goes out of render area doesn't go to impound and just disappear and when you go to impound or garage says that the car is not in the garage - unknown ???

**Comment by hyp3rstrike** [comment]
> `function ImpoundVehicle(vehicle) --local vehicleName = GetLabelText(GetDisplayNameFromVehicleModel(GetEntityModel(vehicle))) local vehicleProps = ESX.Game.GetVehicleProperties(vehicle) TriggerServerEvent('JAM_Garage:ChangeState', vehicleProps.plate, 2) ESX.Game.DeleteVehicle(vehicle) ESX.ShowNotification(_U('impound_successful')) CurrentTask.Busy = false end`
> 
> Replace that function in police job. Should work.

Howdy! Thanks for this. Will give this a go.

**Comment by KilluaZoldyck0099** [comment]
Hyp3rstrike did you replace the function impound with this? And what happened? Cars are showing in the impound?

**Comment by hyp3rstrike** [comment]
> Hyp3rstrike did you replace the function impound with this? And what happened? Cars are showing in the impound?

I haven't implemented the changes as yet as I've been at work all day. When I've implemented them and tested, I'll report back.

**Comment by JustAnotherModder** [comment]
Has this issue been resolved, or..?

**Comment by KilluaZoldyck0099** [comment]
No it hasn’t

**Comment by hyp3rstrike** [comment]
Hi there. Sorry for the delay.

The code you provided has fixed the issue. Thank you. This can now be closed.
